ARG NODE_VERSION=18-alpine

FROM node:${NODE_VERSION}

WORKDIR /app

RUN apk add --no-cache git

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ ./

EXPOSE 3000

CMD ["npm", "run", "start"]
